### ISSUE TITLE
Enable right-click options to work on cycling images

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot.org#12]
New website at https://manubot.org looks great. The cycling images are a nice feature. However, I am having trouble saving / opening in a new tab images that are not first in the rotation. Is it possible to make it so right-click open image in new tab will open the currently displayed image rather than the first image in the rotation?

**Comment by vincerubinetti** [comment]
Yes that should be an easy fix.

It's because all of the images are there in a stack on top of each other, just with an opacity of `0` if they're not the current image. So the first image is probably always at the top of the stack even if it's not visible. It should work just to change the css of the active to have a higher `z-index`.
