### ISSUE TITLE
Add images to website

### ISSUE THREAD

**Issue by dhimmel** [manubot/manubot.org#9]
Currently the website, which is available at http://staging.manubot.org, has placeholders for images.

This issue is for proposing and discussing image ideas.

**Comment by dhimmel** [comment]
Will update this post

## Free and open-source pane

+ [OSI logo](https://opensource.org/logo-usage-guidelines)
+ [manubot/rootstock network graph](https://github.com/manubot/rootstock/network)
+ possibly something from https://gource.io/

**Comment by vincerubinetti** [comment]
Gifs/mp4s would actually be good here. Always better show the motion of something rather than something static. That way we can also show multiple features without having to crowd them into a single image.

This will require some artistic touch and in-person back-and-forth iteration. For this discussion though it'd be helpful to know general ideas for each panel, as Daniel began to list above.

**Comment by dhimmel** [comment]
> Gifs/mp4s would actually be good here

I agree some motion images would be good. Possibly even a simple https://asciinema.org recording somewhere. @vincerubinetti what percent of images should be motion? Would having everything motion be overwhelming? I guess we could always click to play.

**Comment by vincerubinetti** [comment]
@dhimmel Probably just the ones under "At a Glance" and "The Best Parts"
